name: release-main

on:
  release:
    types: [published]
    branches: [main]

jobs:
{%- if cookiecutter.mkdocs == "y" %}
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
{% endif %}
